### ISSUE TITLE
Breaks lightline color scheme

### ISSUE THREAD

**Issue by dahmc** [ellisonleao/gruvbox.nvim#94]
I've seen a few issues here in the last 24h that complained that if you don't have lightline installed, it threw an error, which seemed to have been fixed.

But I actually DO have it :) and the gruvbox theme is now broken:
<img width="403" alt="Screenshot 2022-01-09 at 07 58 57" src="https://user-images.githubusercontent.com/75008413/148672559-a3ace147-5226-42fd-83a4-abcbd20d3912.png">

You can also see that clearly, those aren't gruvbox colors.

This is the unmodified setting for lightline, which stopped working as of today.
```
" Statusline config (Lightline)
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ }
```

**Comment by ellisonleao** [comment]
Should be fixed now. Can you please pull latest?

**Comment by dahmc** [comment]
Still the same exact error on latest

**Comment by CrossR** [comment]
Looks like the way the lightline theme is set is by directly altering the global lightline variables in lua, rather than offering a theme?

Removing `'colorscheme': 'gruvbox',` from my config made it happy and I have gruvbox colours.

**Comment by dahmc** [comment]
@CrossR that only removes the error message for me, the color's still don't change to gruvbox.

**Comment by BarrensZeppelin** [comment]
It works for me if I put the code for initializing the lightline configuration before `colorscheme gruvbox`.

**Comment by perrin4869** [comment]
I have the same problem still

**Comment by ellisonleao** [comment]
Just got back to this one. I've pushed a fix which i think solves the problem. Can you guys verify if it's okay on your side?

**Comment by BarrensZeppelin** [comment]
Lightline support is broken again on master. I get:
`lightline.vim: Could not load colorscheme gruvbox.`
which is unfortunately not very helpful.

**Comment by ellisonleao** [comment]
@BarrensZeppelin just pushed a fix
